### ISSUE TITLE
Would your patch work for the danish version, if it was given as original.apk?

### ISSUE THREAD

**Issue by laurits-mumberg** [ekvanox/adfree-viafree#1]
I am very clueless when it comes to apps :)

**Comment by ekvanox** [comment]
Yes, the same process applies. However, the modification is done by hand and it will hence not be a trivial task.

Precompiled binaries and instructions for installing the Danish version can be found here: https://github.com/ekvanox/adfree-viafree/releases/tag/dk-v.4.6.2 (added in version f4786d5)
